version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: peregrine
      POSTGRES_USER: peregrine
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"

  migrate:
    environment:
      - GO_ENV=docker
    build: .
    command: ["migrate", "-up"]
    depends_on:
      - db
    links:
      - db

  app:
    environment:
      - GO_ENV=docker
      - TBA_API_KEY=${TBA_API_KEY}
    build: .
    command: ["peregrine"]
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate
    links:
      - db
      - migrate
