server:
  httpAddress: localhost:8080
  origin: "*"
  year: 2018
  logJSON: false

tba:
  URL: https://www.thebluealliance.com/api/v3

database:
  user: peregrine
  password: ""
  host: localhost
  port: 5432
  name: peregrine
  sslMode: disable
